// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://atwifqfhtoncwpoxcewv.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImF0d2lmcWZodG9uY3dwb3hjZXd2Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTg3MjM5MzQsImV4cCI6MjA3NDI5OTkzNH0.5Jztc1eFGg5ZyfbdsBMZo4oyPaD5FWOrwVg2iWyh0SI";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});